#!/bin/bash
# Tests for scripts/bump-version.sh — release version propagation.
#
# Each case builds a hermetic sandbox containing only the files the script
# manages, plus scripts/bump-version.sh and scripts/lib/. The script derives
# REPO_ROOT from its own location, so the sandbox layout must mirror the repo.
#
# Covered:
#   1.  --current prints the canonical version
#   2.  --check detects drift and exits 1
#   3.  --sync repairs drift; --check then exits 0
#   4.  patch / minor / major arithmetic
#   5.  explicit X.Y.Z target
#   6.  malformed version rejected
#   7.  bumping to the current version is refused (points at --sync)
#   8.  --dry-run writes nothing
#   9.  YAML comments and placeholders survive the edit
#   10. CHANGELOG [Unreleased] promoted, fresh [Unreleased] opened
#   11. --tag refuses a dirty tree BEFORE writing anything
#   12. --tag commits the bump and creates the annotated tag
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

PASS=0; FAIL=0
ok()  { echo "  PASS: $*"; ((PASS++)) || true; }
bad() { echo "  FAIL: $*"; ((FAIL++)) || true; }

TMPROOT="$(mktemp -d)"
trap 'rm -rf "${TMPROOT}"' EXIT

# new_sandbox NAME CANONICAL_VERSION MIRROR_VERSION
# Builds a sandbox and echoes its path. MIRROR_VERSION lets a case start drifted.
new_sandbox() {
  local name="$1" canon="$2" mirror="$3"
  local sb="${TMPROOT}/${name}"

  mkdir -p "${sb}/scripts" \
           "${sb}/.claude-plugin" \
           "${sb}/plugins/uncle-dev/.codex-plugin" \
           "${sb}/goose" \
           "${sb}/.agents/plugins" \
           "${sb}/skills/uncle-dev-setup-local"

  cp "${REPO_ROOT}/scripts/bump-version.sh" "${sb}/scripts/"
  cp -R "${REPO_ROOT}/scripts/lib" "${sb}/scripts/lib"

  printf '{\n  "name": "uncle-dev",\n  "version": "%s",\n  "license": "MIT"\n}\n' \
    "${canon}" > "${sb}/.claude-plugin/plugin.json"
  printf '{\n  "name": "uncle-dev",\n  "version": "%s",\n  "keywords": ["codex"]\n}\n' \
    "${mirror}" > "${sb}/plugins/uncle-dev/.codex-plugin/plugin.json"
  printf '{\n  "name": "uncle-dev",\n  "version": "%s"\n}\n' \
    "${mirror}" > "${sb}/goose/plugin.json"
  printf '{\n  "name": "uncle-dev",\n  "plugins": [\n    { "name": "uncle-dev", "version": "%s", "skills": ["a", "b"] }\n  ]\n}\n' \
    "${mirror}" > "${sb}/.agents/plugins/marketplace.json"

  # Template YAML with the comment blocks and placeholders the real one carries.
  {
    printf '# .agents/uncle-dev-setup.yaml\n'
    printf '# Uncle Dev project configuration — generated by /uncle-dev-setup\n'
    printf '\n'
    printf 'version: "%s"\n' "${mirror}"
    printf '\n'
    printf '# ── Project metadata ────────────────────────────────\n'
    printf 'project:\n'
    printf '  name: "__PROJECT_NAME__"\n'
  } > "${sb}/skills/uncle-dev-setup-local/uncle-dev-setup.template.yaml"

  {
    printf '# Changelog\n\n'
    printf '## [Unreleased]\n\n'
    printf '### Added\n\n'
    printf -- '- something\n\n'
    printf '## [1.4.1] - 2026-05-30\n'
  } > "${sb}/CHANGELOG.md"

  echo "${sb}"
}

BUMP="scripts/bump-version.sh"

echo "── bump-version.sh ────────────────────────────────────────"

# ── 1. --current ─────────────────────────────────────────────────────────────
SB="$(new_sandbox current 1.5.0 1.5.0)"
OUT="$(cd "${SB}" && bash "${BUMP}" --current 2>/dev/null)"
[[ "${OUT}" == "1.5.0" ]] \
  && ok "--current prints canonical version" \
  || bad "--current expected 1.5.0, got '${OUT}'"

# --next resolves a target without writing anything (release.sh depends on this).
SB="$(new_sandbox next 1.5.0 1.5.0)"
NEXT_OK=1
for pair in "patch 1.5.1" "minor 1.6.0" "major 2.0.0" "9.9.9 9.9.9"; do
  arg="${pair%% *}"; want="${pair##* }"
  got="$(cd "${SB}" && bash "${BUMP}" --next "${arg}" 2>/dev/null)"
  [[ "${got}" == "${want}" ]] || { NEXT_OK=0; bad "--next ${arg}: expected ${want}, got '${got}'"; }
done
[[ "${NEXT_OK}" -eq 1 ]] && ok "--next resolves patch/minor/major/explicit targets"
[[ "$(cd "${SB}" && jq -r .version .claude-plugin/plugin.json)" == "1.5.0" ]] \
  && ok "--next writes nothing" \
  || bad "--next mutated the manifest"
(cd "${SB}" && bash "${BUMP}" --next 2>/dev/null); RC=$?
[[ "${RC}" -ne 0 ]] \
  && ok "--next without an argument is rejected" \
  || bad "--next with no argument should fail"

# ── 2. --check detects drift ─────────────────────────────────────────────────
SB="$(new_sandbox drift 1.5.0 1.4.1)"
OUT="$(cd "${SB}" && bash "${BUMP}" --check 2>&1)"; RC=$?
if [[ "${RC}" -ne 0 ]] && echo "${OUT}" | grep -q 'DRIFT'; then
  ok "--check reports drift and exits non-zero"
else
  bad "--check on drifted sandbox: rc=${RC}, out='${OUT}'"
fi

# ── 3. --sync repairs drift ──────────────────────────────────────────────────
(cd "${SB}" && bash "${BUMP}" --sync >/dev/null 2>&1)
OUT="$(cd "${SB}" && bash "${BUMP}" --check 2>&1)"; RC=$?
[[ "${RC}" -eq 0 ]] \
  && ok "--sync repairs drift; --check then exits 0" \
  || bad "--check after --sync: rc=${RC}, out='${OUT}'"

# --sync must NOT move the canonical version
V="$(cd "${SB}" && jq -r .version .claude-plugin/plugin.json)"
[[ "${V}" == "1.5.0" ]] \
  && ok "--sync leaves the canonical version unchanged" \
  || bad "--sync changed canonical to '${V}'"

# A second --sync must be a true no-op: manifests already at the target are left
# byte-identical rather than rewritten (jq would otherwise renormalize them).
BEFORE="$(cd "${SB}" && cat .claude-plugin/plugin.json goose/plugin.json \
            plugins/uncle-dev/.codex-plugin/plugin.json .agents/plugins/marketplace.json \
            skills/uncle-dev-setup-local/uncle-dev-setup.template.yaml)"
(cd "${SB}" && bash "${BUMP}" --sync >/dev/null 2>&1)
AFTER="$(cd "${SB}" && cat .claude-plugin/plugin.json goose/plugin.json \
            plugins/uncle-dev/.codex-plugin/plugin.json .agents/plugins/marketplace.json \
            skills/uncle-dev-setup-local/uncle-dev-setup.template.yaml)"
[[ "${BEFORE}" == "${AFTER}" ]] \
  && ok "a second --sync is byte-identical (no reformatting churn)" \
  || bad "repeat --sync rewrote already-correct manifests"

# ── 4. arithmetic ────────────────────────────────────────────────────────────
for pair in "patch 1.5.1" "minor 1.6.0" "major 2.0.0"; do
  part="${pair%% *}"; want="${pair##* }"
  SB="$(new_sandbox "arith-${part}" 1.5.0 1.5.0)"
  (cd "${SB}" && bash "${BUMP}" "${part}" >/dev/null 2>&1)
  V="$(cd "${SB}" && jq -r .version .claude-plugin/plugin.json)"
  [[ "${V}" == "${want}" ]] \
    && ok "${part}: 1.5.0 → ${want}" \
    || bad "${part}: expected ${want}, got '${V}'"
done

# ── 5. explicit target propagates to every mirror ────────────────────────────
SB="$(new_sandbox explicit 1.5.0 1.4.1)"
(cd "${SB}" && bash "${BUMP}" 2.3.4 >/dev/null 2>&1)
ALL_OK=1
for f in .claude-plugin/plugin.json plugins/uncle-dev/.codex-plugin/plugin.json goose/plugin.json; do
  [[ "$(cd "${SB}" && jq -r .version "${f}")" == "2.3.4" ]] || ALL_OK=0
done
[[ "$(cd "${SB}" && jq -r '.plugins[0].version' .agents/plugins/marketplace.json)" == "2.3.4" ]] || ALL_OK=0
[[ "$(cd "${SB}" && awk '/^version:/ {gsub(/^version:[[:space:]]*"|"$/,""); print; exit}' \
     skills/uncle-dev-setup-local/uncle-dev-setup.template.yaml)" == "2.3.4" ]] || ALL_OK=0
[[ "${ALL_OK}" -eq 1 ]] \
  && ok "explicit 2.3.4 propagates to all 5 managed manifests" \
  || bad "explicit target did not reach every mirror"

# unrelated JSON keys survive
if [[ "$(cd "${SB}" && jq -r .license .claude-plugin/plugin.json)" == "MIT" ]] \
   && [[ "$(cd "${SB}" && jq -r '.plugins[0].skills | length' .agents/plugins/marketplace.json)" == "2" ]]; then
  ok "unrelated JSON keys preserved"
else
  bad "jq rewrite dropped unrelated keys"
fi

# ── 6. malformed version rejected ────────────────────────────────────────────
SB="$(new_sandbox malformed 1.5.0 1.5.0)"
OUT="$(cd "${SB}" && bash "${BUMP}" 1.5 2>&1)"; RC=$?
V="$(cd "${SB}" && jq -r .version .claude-plugin/plugin.json)"
if [[ "${RC}" -ne 0 && "${V}" == "1.5.0" ]]; then
  ok "malformed version rejected, nothing written"
else
  bad "malformed version: rc=${RC}, version now '${V}'"
fi

# ── 7. same-version refused, points at --sync ────────────────────────────────
OUT="$(cd "${SB}" && bash "${BUMP}" 1.5.0 2>&1)"; RC=$?
if [[ "${RC}" -ne 0 ]] && echo "${OUT}" | grep -q -- '--sync'; then
  ok "bumping to the current version is refused and suggests --sync"
else
  bad "same-version guard: rc=${RC}, out='${OUT}'"
fi

# ── 8. --dry-run writes nothing ──────────────────────────────────────────────
SB="$(new_sandbox dryrun 1.5.0 1.4.1)"
BEFORE="$(cd "${SB}" && cat .claude-plugin/plugin.json .agents/plugins/marketplace.json CHANGELOG.md)"
(cd "${SB}" && bash "${BUMP}" major --dry-run >/dev/null 2>&1)
AFTER="$(cd "${SB}" && cat .claude-plugin/plugin.json .agents/plugins/marketplace.json CHANGELOG.md)"
[[ "${BEFORE}" == "${AFTER}" ]] \
  && ok "--dry-run leaves every file byte-identical" \
  || bad "--dry-run modified files"

# ── 9. YAML comments + placeholders survive ──────────────────────────────────
SB="$(new_sandbox yaml 1.5.0 1.4.1)"
(cd "${SB}" && bash "${BUMP}" minor >/dev/null 2>&1)
TPL="${SB}/skills/uncle-dev-setup-local/uncle-dev-setup.template.yaml"
if grep -q '^# Uncle Dev project configuration' "${TPL}" \
   && grep -q '__PROJECT_NAME__' "${TPL}" \
   && [[ "$(grep -c '^version:' "${TPL}")" -eq 1 ]]; then
  ok "YAML comments, placeholders, and single version: line preserved"
else
  bad "YAML edit damaged comments/placeholders or duplicated version:"
fi

if python3 -c "import yaml,sys; yaml.safe_load(open(sys.argv[1]))" "${TPL}" 2>/dev/null; then
  ok "template YAML still parses after edit"
else
  bad "template YAML no longer parses"
fi

# ── 10. CHANGELOG promotion ──────────────────────────────────────────────────
CL="${SB}/CHANGELOG.md"
if grep -q '^## \[1\.6\.0\] - [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$' "${CL}" \
   && [[ "$(grep -c '^## \[Unreleased\]' "${CL}")" -eq 1 ]] \
   && [[ "$(grep -n '^## ' "${CL}" | head -1 | cut -d: -f2-)" == "## [Unreleased]" ]]; then
  ok "CHANGELOG promoted to [1.6.0] with a fresh [Unreleased] on top"
else
  bad "CHANGELOG promotion wrong: $(grep -n '^## ' "${CL}" | head -3 | tr '\n' ' ')"
fi

# --no-changelog leaves it alone
SB="$(new_sandbox nochangelog 1.5.0 1.5.0)"
BEFORE="$(cat "${SB}/CHANGELOG.md")"
(cd "${SB}" && bash "${BUMP}" patch --no-changelog >/dev/null 2>&1)
[[ "${BEFORE}" == "$(cat "${SB}/CHANGELOG.md")" ]] \
  && ok "--no-changelog leaves CHANGELOG.md untouched" \
  || bad "--no-changelog still modified CHANGELOG.md"

# ── 11. --tag refuses a dirty tree before writing ────────────────────────────
SB="$(new_sandbox dirty 1.5.0 1.5.0)"
(cd "${SB}" && git init -q . && git config user.email t@t && git config user.name t \
   && git add -A && git commit -qm init) >/dev/null 2>&1
echo dirt > "${SB}/dirt.txt"
OUT="$(cd "${SB}" && bash "${BUMP}" minor --tag 2>&1)"; RC=$?
V="$(cd "${SB}" && jq -r .version .claude-plugin/plugin.json)"
if [[ "${RC}" -ne 0 && "${V}" == "1.5.0" ]]; then
  ok "--tag on a dirty tree is refused before any file is written"
else
  bad "--tag dirty-tree guard: rc=${RC}, version now '${V}'"
fi

# ── 12. --tag commits the bump and tags it ───────────────────────────────────
SB="$(new_sandbox tagclean 1.5.0 1.5.0)"
(cd "${SB}" && git init -q . && git config user.email t@t && git config user.name t \
   && git add -A && git commit -qm init) >/dev/null 2>&1
(cd "${SB}" && bash "${BUMP}" minor --tag) >/dev/null 2>&1
TAGS="$(cd "${SB}" && git tag)"
SUBJ="$(cd "${SB}" && git log --format=%s -1)"
CLEAN="$(cd "${SB}" && git status --porcelain)"
if [[ "${TAGS}" == "v1.6.0" && "${SUBJ}" == "chore(release): v1.6.0" && -z "${CLEAN}" ]]; then
  ok "--tag commits 'chore(release): v1.6.0', tags v1.6.0, leaves tree clean"
else
  bad "--tag result: tags='${TAGS}' subject='${SUBJ}' dirty='${CLEAN}'"
fi

# tag must point at the release commit, not an earlier one
POINTS_AT="$(cd "${SB}" && git rev-list -n1 v1.6.0 2>/dev/null)"
HEAD_SHA="$(cd "${SB}" && git rev-parse HEAD)"
[[ "${POINTS_AT}" == "${HEAD_SHA}" ]] \
  && ok "tag v1.6.0 points at the release commit" \
  || bad "tag points at ${POINTS_AT}, HEAD is ${HEAD_SHA}"

echo ""
echo "── Result ────────────────────────────────────────────────"
echo "  PASS: ${PASS}  FAIL: ${FAIL}"
[[ "${FAIL}" -eq 0 ]] || exit 1
